name = "OpenPixelControl"
uuid = "281f80d8-6e88-11e9-078b-b90be1742701"
authors = ["Ronny Bergmann <stackenlichten@ronnybergmann.net>"]
version = "0.1.1"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[compat]
julia = "1"
Colors = ">= 0.9"
